name: Create Pull Request
on:
  push:
    branches:
      - develop
jobs:
  gitPrRelease:
    name: git-pr-release
    runs-on: ubuntu-latest
    steps:
      - name: git-pr-release
        uses: tae124/git-pr-release-action@master
        env:
          GIT_PR_RELEASE_BRANCH_STAGING: develop
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
